version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: licitaApiDb
    restart: "no"

    environment:
      POSTGRES_USER: licitaApiDb
      POSTGRES_PASSWORD: licitaApiDb12345678
      POSTGRES_DB: licitaApiDb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: